### ISSUE TITLE
Few missing steps in the manual install

### ISSUE THREAD

**Issue by meeas** [OWASP/NodeGoat#66] opened 2016-04-15 16:33 UTC
Install grunt with:
    npm install -g grunt
Install required packages on Ubuntu with:
    apt-get install nodejs npm mongodb
Fix Ubuntu's node name change
    sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by meeas** [comment] 2016-04-15 16:35
Even after all of that, I got it started, but when I tried to register a new user, it crashed.  Any ideas:

# npm start

> owasp-nodejs-goat@1.3.0 start /var/www/html
> node server.js

Connected to the database: mongodb://localhost:27017/nodegoat
Express http server listening on port 4000
welcome: Unable to identify user...redirecting to login

/var/www/html/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                        ^
TypeError: Cannot read property 'seq' of null
    at /var/www/html/app/data/user-dao.js:131:42
    at handleCallback (/var/www/html/node_modules/mongodb/lib/utils.js:96:12)
    at /var/www/html/node_modules/mongodb/lib/collection.js:2390:14
    at handleCallback (/var/www/html/node_modules/mongodb/lib/utils.js:96:12)
    at /var/www/html/node_modules/mongodb/lib/db.js:308:5
    at commandCallback (/var/www/html/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1161:9)
    at Callbacks.emit (/var/www/html/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/var/www/html/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:295:23)
    at Socket.<anonymous> (/var/www/html/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at Socket.EventEmitter.emit (events.js:95:17)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by ckarande** [comment] 2016-04-21 20:04
Before starting the server, did you populate DB with seed data by running this grunt task 
`grunt db-reset:development`

**Comment by bencarothers** [comment] 2016-06-20 15:38
I'm having the same issue on a Debian 8 machine.`grunt db-reset:development` is failing to create a `counters` collection. 

Manually inserting a `counters` collection allows you to insert new users.

**Comment by bencarothers** [comment] 2016-06-20 21:04
I edited db-reset.js to insert `counters` as follows: 

`var counter = {_id:"userId", seq:3};
    countersCol = db.collection("counters").insertOne(counter, function(err, result) {
        parseResponse(err, result, "counter.insert");
    });
`

I don't understand the results at all.

Here's output from when this code does not insert `counters` properly:

>> Running "db-reset:development" (db-reset) task
>> Connected to the database: mongodb://localhost:27017/nodegoat
>> Users to insert:
>> {"_id":1,"userName":"admin","firstName":"Node Goat","lastName":"Admin","password":"Admin_123","isAdmin":true}
>> {"_id":2,"userName":"user1","firstName":"John","lastName":"Doe","benefitStartDate":"2030-01-10","password":"User1_123"}
>> {"_id":3,"userName":"user2","firstName":"Will","lastName":"Smith","benefitStartDate":"2025-11-30","password":"User2_123"}
>> users.insertMany
>> {"result":{"ok":1,"n":3},"ops":[{"_id":1,"userName":"admin","firstName":"Node Goat","lastName":"Admin","password":"Admin_123","isAdmin":true},{"_id":2,"userName":"user1","firstName":"John","lastName":"Doe","benefitStartDate":"2030-01-10","password":"User1_123"},{"_id":3,"userName":"user2","firstName":"Will","lastName":"Smith","benefitStartDate":"2025-11-30","password":"User2_123"}],"insertedCount":3,"insertedIds":[1,2,3]}
>> Allocations to insert:
>> {"userId":1,"stocks":28,"funds":2,"bonds":70}
>> {"userId":2,"stocks":9,"funds":33,"bonds":58}
>> {"userId":3,"stocks":21,"funds":26,"bonds":53}
>> counter.insert
>> {"ok":1,"n":1}
>> allocations.insertMany
>> {"result":{"ok":1,"n":3},"ops":[{"userId":1,"stocks":28,"funds":2,"bonds":70,"_id":"576857b47b2cb99f0bca9069"},{"userId":2,"stocks":9,"funds":33,"bonds":58,"_id":"576857b47b2cb99f0bca906a"},{"userId":3,"stocks":21,"funds":26,"bonds":53,"_id":"576857b47b2cb99f0bca906b"}],"insertedCount":3,"insertedIds":["576857b47b2cb99f0bca9069","576857b47b2cb99f0bca906a","576857b47b2cb99f0bca906b"]}

And here's output from when it ran properly after dropping the db and running the command once more:

>> Running "db-reset:development" (db-reset) task
>> Connected to the database: mongodb://localhost:27017/nodegoat
>> Users to insert:
>> {"_id":1,"userName":"admin","firstName":"Node Goat","lastName":"Admin","password":"Admin_123","isAdmin":true}
>> {"_id":2,"userName":"user1","firstName":"John","lastName":"Doe","benefitStartDate":"2030-01-10","password":"User1_123"}
>> {"_id":3,"userName":"user2","firstName":"Will","lastName":"Smith","benefitStartDate":"2025-11-30","password":"User2_123"}
>> users.insertMany
>> {"result":{"ok":1,"n":3},"ops":[{"_id":1,"userName":"admin","firstName":"Node Goat","lastName":"Admin","password":"Admin_123","isAdmin":true},{"_id":2,"userName":"user1","firstName":"John","lastName":"Doe","benefitStartDate":"2030-01-10","password":"User1_123"},{"_id":3,"userName":"user2","firstName":"Will","lastName":"Smith","benefitStartDate":"2025-11-30","password":"User2_123"}],"insertedCount":3,"insertedIds":[1,2,3]}
>> Allocations to insert:
>> {"userId":1,"stocks":28,"funds":2,"bonds":70}
>> {"userId":2,"stocks":9,"funds":33,"bonds":58}
>> {"userId":3,"stocks":21,"funds":26,"bonds":53}
>> counter.insert
>> {"ok":1,"n":1}
>> allocations.insertMany
>> {"result":{"ok":1,"n":3},"ops":[{"userId":1,"stocks":28,"funds":2,"bonds":70,"_id":"576857b47b2cb99f0bca9069"},{"userId":2,"stocks":9,"funds":33,"bonds":58,"_id":"576857b47b2cb99f0bca906a"},{"userId":3,"stocks":21,"funds":26,"bonds":53,"_id":"576857b47b2cb99f0bca906b"}],"insertedCount":3,"insertedIds":["576857b47b2cb99f0bca9069","576857b47b2cb99f0bca906a","576857b47b2cb99f0bca906b"]}

**Comment by SJCaldwell** [comment] 2016-06-20 23:38
Note: @bencarothers  and I were working on getting the app to run together. We were running on a 32-bit debian jessie. 

I tried to reproduce the issue on my Mac just now, running the same version of node and npm and could not - original script works with no changes. Seems to be architecture dependent.

**Comment by ckarande** [comment] 2016-06-21 20:50
@bencarothers @SJCaldwell Thanks for reporting the issue and helping in troubleshoot it. I will try it on a 32-bit debian jessie instance to know what is causing the counters not insert properly.

**Comment by binarymist** [comment] 2016-09-15 21:04
Is this one still waiting on you @ckarande ? Does something need to be tested here?

**Comment by ckarande** [comment] 2017-02-22 18:07
Looks like the script works. I am closing the issue. Please comment or reopen if any more details.

**Closed by ckarande** 2017-02-22 18:07 UTC
